"""init all tables

Revision ID: 3876a7bdd7ff
Revises: 
Create Date: 2026-08-04 17:52:41.316317

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3876a7bdd7ff'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device_type_threshold',
    sa.Column('device_type', sa.String(length=30), nullable=False, comment='设备类型'),
    sa.Column('point_type', sa.String(length=20), nullable=False, comment='点位类型'),
    sa.Column('unit', sa.String(length=20), nullable=True, comment='单位'),
    sa.Column('alarm_low_default', sa.Float(), nullable=True, comment='默认报警下限'),
    sa.Column('alarm_high_default', sa.Float(), nullable=True, comment='默认报警上限'),
    sa.Column('trend_window_default', sa.Integer(), nullable=False, comment='默认趋势窗口（采样点数）'),
    sa.Column('trend_delta_default', sa.Float(), nullable=False, comment='默认趋势上升幅度阈值'),
    sa.Column('collect_interval_seconds_default', sa.Integer(), nullable=False, comment='默认采集频率（秒）'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_type', 'point_type', name='uq_type_point')
    )
    op.create_index(op.f('ix_device_type_threshold_device_type'), 'device_type_threshold', ['device_type'], unique=False)
    op.create_table('sys_user',
    sa.Column('username', sa.String(length=50), nullable=False, comment='用户名'),
    sa.Column('password_hash', sa.String(length=255), nullable=False, comment='密码哈希'),
    sa.Column('real_name', sa.String(length=50), nullable=True, comment='姓名'),
    sa.Column('phone', sa.String(length=20), nullable=True, comment='手机号'),
    sa.Column('role', sa.String(length=30), nullable=False, comment='角色: ADMIN/MAINTENANCE_WORKER/VIEWER'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='状态: ACTIVE/DISABLED'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('tenant_id', sa.String(length=64), nullable=False, comment='租户ID（预留）'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sys_user_tenant_id'), 'sys_user', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_sys_user_username'), 'sys_user', ['username'], unique=True)
    op.create_table('warehouse',
    sa.Column('name', sa.String(length=100), nullable=False, comment='仓库名称'),
    sa.Column('address', sa.String(length=255), nullable=True, comment='仓库地址'),
    sa.Column('contact_name', sa.String(length=50), nullable=True, comment='联系人'),
    sa.Column('contact_phone', sa.String(length=20), nullable=True, comment='联系电话'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='状态: ACTIVE/DISABLED'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('tenant_id', sa.String(length=64), nullable=False, comment='租户ID（预留）'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_warehouse_tenant_id'), 'warehouse', ['tenant_id'], unique=False)
    op.create_table('device',
    sa.Column('warehouse_id', sa.Integer(), nullable=False, comment='所属仓库'),
    sa.Column('device_code', sa.String(length=50), nullable=False, comment='设备编号'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='设备名称'),
    sa.Column('device_type', sa.String(length=30), nullable=False, comment='设备类型: CONVEYOR/STACKER/AGV/SORTER/FORKLIFT'),
    sa.Column('brand', sa.String(length=50), nullable=True, comment='品牌'),
    sa.Column('model', sa.String(length=50), nullable=True, comment='型号'),
    sa.Column('location', sa.String(length=100), nullable=True, comment='安装位置'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='状态: RUNNING/STOPPED/MAINTENANCE/SCRAPPED'),
    sa.Column('purchase_date', sa.Date(), nullable=True, comment='采购日期'),
    sa.Column('install_date', sa.Date(), nullable=True, comment='安装日期'),
    sa.Column('scrap_date', sa.Date(), nullable=True, comment='报废日期'),
    sa.Column('lifespan_years', sa.Integer(), nullable=True, comment='设计寿命（年）'),
    sa.Column('supplier', sa.String(length=100), nullable=True, comment='供应商'),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=True, comment='采购价格'),
    sa.Column('description', sa.Text(), nullable=True, comment='备注'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('tenant_id', sa.String(length=64), nullable=False, comment='租户ID（预留）'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouse.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_device_device_code'), 'device', ['device_code'], unique=True)
    op.create_index(op.f('ix_device_device_type'), 'device', ['device_type'], unique=False)
    op.create_index(op.f('ix_device_status'), 'device', ['status'], unique=False)
    op.create_index(op.f('ix_device_tenant_id'), 'device', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_device_warehouse_id'), 'device', ['warehouse_id'], unique=False)
    op.create_table('notification',
    sa.Column('user_id', sa.Integer(), nullable=False, comment='接收人'),
    sa.Column('notify_type', sa.String(length=20), nullable=False, comment='类型: ALERT/STOCK/WORK_ORDER'),
    sa.Column('title', sa.String(length=200), nullable=False, comment='标题'),
    sa.Column('content', sa.Text(), nullable=True, comment='内容'),
    sa.Column('ref_type', sa.String(length=30), nullable=True, comment='关联对象类型'),
    sa.Column('ref_id', sa.Integer(), nullable=True, comment='关联对象ID'),
    sa.Column('is_read', sa.Boolean(), nullable=False, comment='已读'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('tenant_id', sa.String(length=64), nullable=False, comment='租户ID（预留）'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['user_id'], ['sys_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_notify_type'), 'notification', ['notify_type'], unique=False)
    op.create_index(op.f('ix_notification_tenant_id'), 'notification', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_notification_user_id'), 'notification', ['user_id'], unique=False)
    op.create_table('spare_part',
    sa.Column('warehouse_id', sa.Integer(), nullable=False, comment='仓库'),
    sa.Column('part_code', sa.String(length=50), nullable=False, comment='备件编号'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='备件名称'),
    sa.Column('spec', sa.String(length=100), nullable=True, comment='规格型号'),
    sa.Column('unit', sa.String(length=20), nullable=True, comment='单位'),
    sa.Column('stock_quantity', sa.Integer(), nullable=False, comment='当前库存'),
    sa.Column('safe_quantity', sa.Integer(), nullable=False, comment='安全库存'),
    sa.Column('storage_location', sa.String(length=50), nullable=True, comment='库位'),
    sa.Column('supplier', sa.String(length=100), nullable=True, comment='供应商'),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True, comment='参考单价'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='状态: ACTIVE/DISABLED'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('tenant_id', sa.String(length=64), nullable=False, comment='租户ID（预留）'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouse.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('part_code')
    )
    op.create_index(op.f('ix_spare_part_tenant_id'), 'spare_part', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_spare_part_warehouse_id'), 'spare_part', ['warehouse_id'], unique=False)
    op.create_table('device_point',
    sa.Column('device_id', sa.Integer(), nullable=False, comment='所属设备'),
    sa.Column('point_code', sa.String(length=50), nullable=False, comment='点位编号'),
    sa.Column('point_type', sa.String(length=20), nullable=False, comment='点位类型: VIBRATION/TEMPERATURE/CURRENT'),
    sa.Column('unit', sa.String(length=20), nullable=True, comment='单位'),
    sa.Column('alarm_low', sa.Float(), nullable=True, comment='报警下限'),
    sa.Column('alarm_high', sa.Float(), nullable=True, comment='报警上限'),
    sa.Column('trend_window', sa.Integer(), nullable=False, comment='趋势检测窗口（采样点数）'),
    sa.Column('trend_delta', sa.Float(), nullable=False, comment='趋势检测上升幅度阈值'),
    sa.Column('collect_interval_seconds', sa.Integer(), nullable=False, comment='采集频率（秒）'),
    sa.Column('enabled', sa.Boolean(), nullable=False, comment='是否启用'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('tenant_id', sa.String(length=64), nullable=False, comment='租户ID（预留）'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['device_id'], ['device.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_id', 'point_code', name='uq_device_point_code')
    )
    op.create_index(op.f('ix_device_point_device_id'), 'device_point', ['device_id'], unique=False)
    op.create_index(op.f('ix_device_point_point_type'), 'device_point', ['point_type'], unique=False)
    op.create_index(op.f('ix_device_point_tenant_id'), 'device_point', ['tenant_id'], unique=False)
    op.create_table('health_record',
    sa.Column('device_id', sa.Integer(), nullable=False, comment='设备'),
    sa.Column('score', sa.Float(), nullable=False, comment='健康度评分 0-100'),
    sa.Column('level', sa.String(length=20), nullable=False, comment='等级: HEALTHY/SUB_HEALTHY/ABNORMAL'),
    sa.Column('factor_json', sa.JSON(), nullable=True, comment='影响因素（哪些点位/扣分原因）'),
    sa.Column('computed_at', sa.DateTime(), nullable=False, comment='计算时间'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('tenant_id', sa.String(length=64), nullable=False, comment='租户ID（预留）'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['device_id'], ['device.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_device_computed', 'health_record', ['device_id', 'computed_at'], unique=False)
    op.create_index(op.f('ix_health_record_device_id'), 'health_record', ['device_id'], unique=False)
    op.create_index(op.f('ix_health_record_tenant_id'), 'health_record', ['tenant_id'], unique=False)
    op.create_table('alert',
    sa.Column('device_id', sa.Integer(), nullable=False, comment='设备'),
    sa.Column('point_id', sa.Integer(), nullable=True, comment='点位（数据链路告警可空）'),
    sa.Column('alert_type', sa.String(length=30), nullable=False, comment='类型: THRESHOLD_HIGH/THRESHOLD_LOW/TREND/ANOMALY/DATA_LINK'),
    sa.Column('trigger_layer', sa.String(length=30), nullable=False, comment='触发层: THRESHOLD/TREND/ISOLATION_FOREST/DATA_LINK'),
    sa.Column('level', sa.String(length=20), nullable=False, comment='级别: INFO/WARNING/CRITICAL'),
    sa.Column('title', sa.String(length=200), nullable=False, comment='标题'),
    sa.Column('description', sa.Text(), nullable=True, comment='描述/证据'),
    sa.Column('metric_value', sa.Float(), nullable=True, comment='触发时指标值'),
    sa.Column('threshold', sa.Float(), nullable=True, comment='触发的阈值'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='状态: PENDING/HANDLED/IGNORED/CONVERTED'),
    sa.Column('source', sa.String(length=20), nullable=False, comment='来源: AUTO/MANUAL'),
    sa.Column('handled_by', sa.String(length=50), nullable=True, comment='处理人'),
    sa.Column('handled_at', sa.DateTime(), nullable=True, comment='处理时间'),
    sa.Column('handle_note', sa.Text(), nullable=True, comment='处理说明'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('tenant_id', sa.String(length=64), nullable=False, comment='租户ID（预留）'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['device_id'], ['device.id'], ),
    sa.ForeignKeyConstraint(['point_id'], ['device_point.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alert_alert_type'), 'alert', ['alert_type'], unique=False)
    op.create_index(op.f('ix_alert_device_id'), 'alert', ['device_id'], unique=False)
    op.create_index(op.f('ix_alert_status'), 'alert', ['status'], unique=False)
    op.create_index(op.f('ix_alert_tenant_id'), 'alert', ['tenant_id'], unique=False)
    op.create_table('sensor_data',
    sa.Column('device_id', sa.Integer(), nullable=False, comment='设备（冗余，加速按设备查询）'),
    sa.Column('device_point_id', sa.Integer(), nullable=False, comment='采集点位'),
    sa.Column('value', sa.Float(), nullable=False, comment='采集值'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='数据状态: NORMAL/MISSING/ABNORMAL'),
    sa.Column('collected_at', sa.DateTime(), nullable=False, comment='采集时间'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('tenant_id', sa.String(length=64), nullable=False, comment='租户ID（预留）'),
    sa.ForeignKeyConstraint(['device_id'], ['device.id'], ),
    sa.ForeignKeyConstraint(['device_point_id'], ['device_point.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_device_time', 'sensor_data', ['device_id', 'collected_at'], unique=False)
    op.create_index('idx_point_time', 'sensor_data', ['device_point_id', 'collected_at'], unique=False)
    op.create_index(op.f('ix_sensor_data_collected_at'), 'sensor_data', ['collected_at'], unique=False)
    op.create_index(op.f('ix_sensor_data_device_id'), 'sensor_data', ['device_id'], unique=False)
    op.create_index(op.f('ix_sensor_data_tenant_id'), 'sensor_data', ['tenant_id'], unique=False)
    op.create_table('work_order',
    sa.Column('warehouse_id', sa.Integer(), nullable=False, comment='仓库'),
    sa.Column('device_id', sa.Integer(), nullable=False, comment='设备'),
    sa.Column('order_no', sa.String(length=50), nullable=False, comment='工单编号'),
    sa.Column('title', sa.String(length=200), nullable=False, comment='工单标题'),
    sa.Column('description', sa.Text(), nullable=True, comment='问题描述'),
    sa.Column('order_type', sa.String(length=20), nullable=False, comment='类型: REPAIR/MAINTENANCE/INSPECTION/OTHER'),
    sa.Column('source', sa.String(length=20), nullable=False, comment='来源: ALERT/PLAN/MANUAL'),
    sa.Column('alert_id', sa.Integer(), nullable=True, comment='来源预警（可空）'),
    sa.Column('priority', sa.String(length=20), nullable=False, comment='优先级: LOW/MEDIUM/HIGH/URGENT'),
    sa.Column('assignee_id', sa.Integer(), nullable=True, comment='指派人'),
    sa.Column('status', sa.String(length=30), nullable=False, comment='状态: PENDING_ASSIGN/PENDING_EXECUTE/IN_PROGRESS/PENDING_ACCEPT/COMPLETED/CANCELLED'),
    sa.Column('scheduled_start', sa.DateTime(), nullable=True, comment='计划开始'),
    sa.Column('scheduled_end', sa.DateTime(), nullable=True, comment='计划结束'),
    sa.Column('actual_start', sa.DateTime(), nullable=True, comment='实际开始'),
    sa.Column('actual_end', sa.DateTime(), nullable=True, comment='实际结束'),
    sa.Column('result', sa.Text(), nullable=True, comment='处理结果'),
    sa.Column('created_by', sa.String(length=50), nullable=True, comment='创建人'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('tenant_id', sa.String(length=64), nullable=False, comment='租户ID（预留）'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['alert_id'], ['alert.id'], ),
    sa.ForeignKeyConstraint(['assignee_id'], ['sys_user.id'], ),
    sa.ForeignKeyConstraint(['device_id'], ['device.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouse.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_no')
    )
    op.create_index(op.f('ix_work_order_device_id'), 'work_order', ['device_id'], unique=False)
    op.create_index(op.f('ix_work_order_priority'), 'work_order', ['priority'], unique=False)
    op.create_index(op.f('ix_work_order_status'), 'work_order', ['status'], unique=False)
    op.create_index(op.f('ix_work_order_tenant_id'), 'work_order', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_work_order_warehouse_id'), 'work_order', ['warehouse_id'], unique=False)
    op.create_table('maintenance_record',
    sa.Column('device_id', sa.Integer(), nullable=False, comment='设备'),
    sa.Column('work_order_id', sa.Integer(), nullable=True, comment='来源工单（可空）'),
    sa.Column('maintenance_type', sa.String(length=20), nullable=False, comment='维保类型: REPAIR/MAINTENANCE/INSPECTION'),
    sa.Column('description', sa.Text(), nullable=True, comment='维保内容'),
    sa.Column('cost', sa.Numeric(precision=10, scale=2), nullable=True, comment='费用'),
    sa.Column('executed_by', sa.String(length=50), nullable=True, comment='执行人'),
    sa.Column('executed_at', sa.DateTime(), nullable=True, comment='执行时间'),
    sa.Column('next_due_date', sa.Date(), nullable=True, comment='下次保养日期'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('tenant_id', sa.String(length=64), nullable=False, comment='租户ID（预留）'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['device_id'], ['device.id'], ),
    sa.ForeignKeyConstraint(['work_order_id'], ['work_order.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_maintenance_record_device_id'), 'maintenance_record', ['device_id'], unique=False)
    op.create_index(op.f('ix_maintenance_record_tenant_id'), 'maintenance_record', ['tenant_id'], unique=False)
    op.create_table('stock_record',
    sa.Column('spare_part_id', sa.Integer(), nullable=False, comment='备件'),
    sa.Column('change_type', sa.String(length=20), nullable=False, comment='类型: INBOUND/OUTBOUND/WORK_ORDER/INVENTORY/LOSS'),
    sa.Column('quantity', sa.Integer(), nullable=False, comment='变动数量（正负）'),
    sa.Column('balance_after', sa.Integer(), nullable=False, comment='变动后余量'),
    sa.Column('related_work_order_id', sa.Integer(), nullable=True, comment='关联工单'),
    sa.Column('operator', sa.String(length=50), nullable=True, comment='操作人'),
    sa.Column('remark', sa.Text(), nullable=True, comment='备注'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('tenant_id', sa.String(length=64), nullable=False, comment='租户ID（预留）'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['related_work_order_id'], ['work_order.id'], ),
    sa.ForeignKeyConstraint(['spare_part_id'], ['spare_part.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_record_spare_part_id'), 'stock_record', ['spare_part_id'], unique=False)
    op.create_index(op.f('ix_stock_record_tenant_id'), 'stock_record', ['tenant_id'], unique=False)
    op.create_table('work_order_part',
    sa.Column('work_order_id', sa.Integer(), nullable=False, comment='工单'),
    sa.Column('spare_part_id', sa.Integer(), nullable=False, comment='备件'),
    sa.Column('quantity', sa.Integer(), nullable=False, comment='数量'),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=True, comment='单价'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('tenant_id', sa.String(length=64), nullable=False, comment='租户ID（预留）'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['spare_part_id'], ['spare_part.id'], ),
    sa.ForeignKeyConstraint(['work_order_id'], ['work_order.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_work_order_part_tenant_id'), 'work_order_part', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_work_order_part_work_order_id'), 'work_order_part', ['work_order_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_work_order_part_work_order_id'), table_name='work_order_part')
    op.drop_index(op.f('ix_work_order_part_tenant_id'), table_name='work_order_part')
    op.drop_table('work_order_part')
    op.drop_index(op.f('ix_stock_record_tenant_id'), table_name='stock_record')
    op.drop_index(op.f('ix_stock_record_spare_part_id'), table_name='stock_record')
    op.drop_table('stock_record')
    op.drop_index(op.f('ix_maintenance_record_tenant_id'), table_name='maintenance_record')
    op.drop_index(op.f('ix_maintenance_record_device_id'), table_name='maintenance_record')
    op.drop_table('maintenance_record')
    op.drop_index(op.f('ix_work_order_warehouse_id'), table_name='work_order')
    op.drop_index(op.f('ix_work_order_tenant_id'), table_name='work_order')
    op.drop_index(op.f('ix_work_order_status'), table_name='work_order')
    op.drop_index(op.f('ix_work_order_priority'), table_name='work_order')
    op.drop_index(op.f('ix_work_order_device_id'), table_name='work_order')
    op.drop_table('work_order')
    op.drop_index(op.f('ix_sensor_data_tenant_id'), table_name='sensor_data')
    op.drop_index(op.f('ix_sensor_data_device_id'), table_name='sensor_data')
    op.drop_index(op.f('ix_sensor_data_collected_at'), table_name='sensor_data')
    op.drop_index('idx_point_time', table_name='sensor_data')
    op.drop_index('idx_device_time', table_name='sensor_data')
    op.drop_table('sensor_data')
    op.drop_index(op.f('ix_alert_tenant_id'), table_name='alert')
    op.drop_index(op.f('ix_alert_status'), table_name='alert')
    op.drop_index(op.f('ix_alert_device_id'), table_name='alert')
    op.drop_index(op.f('ix_alert_alert_type'), table_name='alert')
    op.drop_table('alert')
    op.drop_index(op.f('ix_health_record_tenant_id'), table_name='health_record')
    op.drop_index(op.f('ix_health_record_device_id'), table_name='health_record')
    op.drop_index('idx_device_computed', table_name='health_record')
    op.drop_table('health_record')
    op.drop_index(op.f('ix_device_point_tenant_id'), table_name='device_point')
    op.drop_index(op.f('ix_device_point_point_type'), table_name='device_point')
    op.drop_index(op.f('ix_device_point_device_id'), table_name='device_point')
    op.drop_table('device_point')
    op.drop_index(op.f('ix_spare_part_warehouse_id'), table_name='spare_part')
    op.drop_index(op.f('ix_spare_part_tenant_id'), table_name='spare_part')
    op.drop_table('spare_part')
    op.drop_index(op.f('ix_notification_user_id'), table_name='notification')
    op.drop_index(op.f('ix_notification_tenant_id'), table_name='notification')
    op.drop_index(op.f('ix_notification_notify_type'), table_name='notification')
    op.drop_table('notification')
    op.drop_index(op.f('ix_device_warehouse_id'), table_name='device')
    op.drop_index(op.f('ix_device_tenant_id'), table_name='device')
    op.drop_index(op.f('ix_device_status'), table_name='device')
    op.drop_index(op.f('ix_device_device_type'), table_name='device')
    op.drop_index(op.f('ix_device_device_code'), table_name='device')
    op.drop_table('device')
    op.drop_index(op.f('ix_warehouse_tenant_id'), table_name='warehouse')
    op.drop_table('warehouse')
    op.drop_index(op.f('ix_sys_user_username'), table_name='sys_user')
    op.drop_index(op.f('ix_sys_user_tenant_id'), table_name='sys_user')
    op.drop_table('sys_user')
    op.drop_index(op.f('ix_device_type_threshold_device_type'), table_name='device_type_threshold')
    op.drop_table('device_type_threshold')
    # ### end Alembic commands ###
